name: "fetch_upstream"

on:
  schedule:
    - cron: "0 0 * * *"
  
  workflow_dispatch:

jobs:
  check: # checks for new commits in upstream
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # https://stackoverflow.com/questions/65499626/trigger-github-actions-if-push-in-another-repo
      - name: fetch
        run: |
          #!/usr/bin/env bash
          url="https://api.github.com/repos/dawsers/scroll/commits/REL1_36"
          exit $(curl -s $url | jq -r "((now - (.commit.author.date | fromdateiso8601) )  / (60*60*24)  | trunc)")
