name: "flake_update"

on:
  workflow_run:
    workflows: ["fetch_upstream"]
    types: [completed]

  workflow_dispatch:

jobs:
  update: # updates flake.lock automatically
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write
      issues: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/determinate-nix-action@v3
      - uses: DeterminateSystems/update-flake-lock@main
        id: update
      - run: "gh pr merge --auto --merge ${{ steps.update.outputs.pull-request-number }}"
        env:
          GH_TOKEN: ${{ github.token }}